### ISSUE TITLE
NoSuchElementException when trying to run

### ISSUE THREAD

**Issue by green-john** [bluerogue251/DBSubsetter#141]
First of all, thank you for this. DBSubsetter is exactly what I was looking for. Now, I haven't been able to run it, and I get the following error:

```
Exception in thread "main" java.util.NoSuchElementException: key not found: trw.dbsubsetter.db.package$Table@1c72da34
        at scala.collection.MapLike.default(MapLike.scala:232)
        at scala.collection.MapLike.default$(MapLike.scala:231)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike.apply(MapLike.scala:141)
        at scala.collection.MapLike.apply$(MapLike.scala:140)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at trw.dbsubsetter.db.SchemaInfoRetrieval$.$anonfun$getSchemaInfo$23(SchemaInfoRetrieval.scala:107)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at trw.dbsubsetter.db.SchemaInfoRetrieval$.getSchemaInfo(SchemaInfoRetrieval.scala:106)
        at trw.dbsubsetter.ApplicationRunner$.run(ApplicationRunner.scala:23)
        at trw.dbsubsetter.Application$.delayedEndpoint$trw$dbsubsetter$Application$1(Application.scala:4)
        at trw.dbsubsetter.Application$delayedInit$body.apply(Application.scala:3)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at trw.dbsubsetter.Application$.main(Application.scala:3)
        at trw.dbsubsetter.Application.main(Application.scala)
```

I was wondering if there's a way to show more info that will allow me to better debug the issue (like what is missing). Thank you for the help in advance.

**Comment by bluerogue251** [comment]
Hi @green-john! Sorry for the delayed response -- I had my notifications turned off by accident. Improving the error messages is a great suggestion, and I should be able to add support for better error messages within a week or two.

To unblock you in the meantime, I looked into the stack trace you shared. This particular error occurs when there is a table in the database which is  missing a primary key, or for which DBSubsetter is unable to autodetect the primary key. If you are able to find a table in your origin database that is missing a primary key, then possible workarounds include:
* Specifying the missing primary key via the `--primaryKey` command line option
* Excluding the table in question via the `--excludeTable` command line option
* Adding a primary key onto the table in your origin database

The `$ java -jar /path/to/DBSubsetter.jar --help` command should have some further details about the `--primaryKey` and `--excludeTable` options if you decide to pursue those. Let me know if you run into any other errors and I'll gladly investigate.

**Comment by bluerogue251** [comment]
Release [v1.0.0-beta.6](https://github.com/bluerogue251/DBSubsetter/releases) and above now contain clearer error messages for common misconfigurations, and also contain bug fixes related to your reported issue.

Closing this issue for now. Thank you for the feedback!
